### ISSUE TITLE
Zabbix 2.2.2 - failure to insert items history table

### ISSUE THREAD

**Issue by rudaporto** [blackboard/zabbix-ext#1]
Hi,

I installed db_partition on my zabbix server version 2.2.2 and now it can not insert items on the history table:

 17306:20140321:115103.729 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  missing FROM-clause entry for table "new"
LINE 3:                ( NEW.itemid, NEW.clock, NEW.value, NEW.ns )
                         ^
QUERY:  INSERT INTO HISTORY_m201403
               ( itemid, clock, value, ns ) VALUES 
               ( NEW.itemid, NEW.clock, NEW.value, NEW.ns )
CONTEXT:  PL/pgSQL function "history_insert_trigger" line 8 at EXECUTE statement
 [insert into history (itemid,clock,ns,value) values (50960,1395413463,144645872,158403.282337),(49642,1395413461,107720049,44.890000),(47790,1395413463,191054185,19.000000),(50707,1395413463,305981637,9.306490),(50910,1395413463,352969542,99.146752),(50940,1395413463,364441388,97.402444),(50880,1395413463,397502199,0.019043),(25780,1395413463,397823976,2.930000),(50990,1395413463,399559598,0.296047),(25761,1395413463,408840753,23.883236),(29490,1395413463,466904280,0.195127),(49061,1395413463,467598857,0.180000),(29510,1395413463,469511121,0.020000),(49871,1395413463,471518393,0.025183),(50936,1395413463,606863681,2.597556),(50961,1395413463,632334504,0.000000),(50991,1395413463,680972893,0.055596),(49872,1395413463,700821136,6.471921),(50881,1395413463,721739741,97.884484),(28836,1395413463,724026456,209.256915);
insert into history_uint (itemid,clock,ns,value) values (31230,1395413463,145112595,0),(50909,1395413463,157899944,3782867),(49643,1395413461,107720049,1),(49641,1395413461,107720049,0),(49050,1395413463,364163688,1),(48930,1395413463,371498153,0),(25530,1395413463,405526153,0),(25590,1395413463,408608199,1),(25531,1395413463,409893363,1),(49051,1395413463,417542964,0),(31231,1395413463,468949812,90),(48870,1395413463,514739820,0),(50851,1395413463,678939475,1),(49832,1395413463,690445364,1),(49052,1395413463,699608445,8),(31232,1395413463,700237380,900),(24992,1395413463,704250129,1);
]

Something is not working, it can be my environment or it's a bug?

**Comment by lguoyu** [comment]
Hi rudaporto,

Thanks for the comments, we will get back to you after investigating.

**Comment by rudaporto** [comment]
First, I did a workaround solution, hardcode the monthly table on the trigger, and schedule update at fisrt second of first day each new month.

I guess the dynamic generation of the store procedure code don't compile well and the NEW special variables are not been correct interpreted at code generation, becouse it's inside ' '.

Now I discorver a way to correct these procedures, as follow:

-- Create the trigger function for table ( HISTORY )
CREATE OR REPLACE FUNCTION HISTORY_insert_trigger()
RETURNS TRIGGER AS $$
DECLARE
insert_sql TEXT;
BEGIN
insert_sql:= 'INSERT INTO HISTORY_m' || to_char(to_timestamp(NEW.CLOCK),'yyyymm') || '
( itemid, clock, value, ns ) VALUES 
( $1.itemid, $1.clock, $1.value, $1.ns )';
EXECUTE insert_sql USING NEW;
RETURN NULL;
END
$$ LANGUAGE plpgsql
;

I know this code is also dynamic generated, but change, and to fix this the pgsql/zabbix_maintaince.sql script should be patched.

**Comment by nizhi** [comment]
We fixed the bug, thanks a lot!
