### ISSUE TITLE
Error with JMX monitoring

### ISSUE THREAD

**Issue by threesir** [blackboard/zabbix-ext#3]
Hi, All

I got a problem with JMX monitoring when i follow the article of How to deploy Zabbix agents for Learn Template Suite.

I have a zabbix server A with two clients B and C. Now i can successfully monitor the system status with B and C from my server A. However once i active the Java Gateway, i only can see there is no issue with the connection from client server to Zabbix server (The host status shows green light both for zabbix service and JMX), but i am not able to catch the real JMX data from B and C. Can anyone offer some ideas?

Also i would like to know, does the client server also need to state the Java Gateway address (But the client server only have the agent service, where did i to add the Java gateway address)? Or i can listen the address for B and C from zabbix server? (Currently the listen IP is 0.0.0.0, the Java Gateway wont start if i change the listen IP to address of B or C)

For the bb-config, do i need to put -Djava.rmi.server.hostname as well?

Thanks.

**Comment by lguoyu** [comment]
Hi Threesir,

I assume that you already enabled JMX of Learn, can you check if you can connect JMX of Learn with JConsole? You can reference http://docs.oracle.com/javase/7/docs/technotes/guides/management/jconsole.html for how to use it.

In terms of settings.sh of Zabbix Java Gateway, the listen IP should be the server of zabbix server, not client server, that is to say "0.0.0.0" should be fine if your zabbix server and zabbix Java Gateway are in the same server. Make sure the listen port is the same with the JavaGatewayPort in zabbix_server.conf. 

Also, is there any log in zabbix_java.log?

**Comment by threesir** [comment]
Hi Yu Li,

Thank you for your information.

The Java log 
![zabbix_java](https://cloud.githubusercontent.com/assets/7834207/3266539/dfc81962-f2b3-11e3-9abc-d544da5b71d8.PNG)
says connection refused, (error msg: WARN  com.zabbix.gateway.SocketProcessor - error processing request
com.zabbix.gateway.ZabbixException: java.rmi.ConnectException: Connection refused to host: 192.168.80.120; nested exception is:java.net.ConnectException: Connection refused)

However I had a successful Jconsole connection to  the agent server.
![jconsole](https://cloud.githubusercontent.com/assets/7834207/3266482/625e05f6-f2b1-11e3-8952-9ea0b7ff85f0.PNG)

And now the problem is i am not able monitoring the JMX status of my agent server from my zabbix server.

Here are my sample,   (192.168.80.120 is zabbix server, 192.168.80.188 is the agent server)

server.conf on zabbix server
JavaGateway=192.168.80.120
JavaGatewayPort=10052
StartJavaPollers=5
PidFile=/var/run/zabbix/zabbix_server.pid

Java gateway on zabbix server
LISTEN_IP="0.0.0.0"
LISTEN_PORT=10052
PID_FILE="/var/run/zabbix/zabbix_java.pid"
START_POLLERS=5

Agentd.conf on app server
Server=192.168.80.120
ServerActive=192.168.80.120
Hostname=192.168.80.188

Can you please help to take a look?

Really appreciate your help!

Best Regards,
BL

**Comment by lguoyu** [comment]
Is there any firewall on the app server? Can you try if you can connect to app server with JConsole from your zabbix server(192.168.80.120)?

Can you post your host configuration of the app server(I meant the configuration on UI of zabbix)?

**Comment by threesir** [comment]
Hi Yu Li,

I have disabled the firewall both for app server and zabbix server.

The screenshot i sent in the last note shows that i can do the jconsole to app server from zabbix server. And for the zabbix server, it can obtain the system usage data from the app server, but only failed to load the Java.

This is the host configuration page.
![host config](https://cloud.githubusercontent.com/assets/7834207/3266766/9d3c6bb8-f2bb-11e3-9181-d4a81ba6d96d.PNG)

Thank you!
BL

**Comment by lguoyu** [comment]
Sorry, I meant the detail of host configuration of 192.168.80.188(clicking 192.168.80.188 can enter that page).

**Comment by threesir** [comment]
Here are all the setting pages
![host config](https://cloud.githubusercontent.com/assets/7834207/3267078/7cee1020-f2c3-11e3-8c13-0c0584a37ebb.png)

Thank You!
BL

**Comment by lguoyu** [comment]
Everything looks good, but it's weird that the log reports "Connection refused to host: 192.168.80.120;", the connection should be made to 192.168.80.188 instead of 120.
I assume none authentication needed to connect to JMX,  am I correct?

Any log from zabbix_server.log?

**Comment by threesir** [comment]
Hi Yu Li,

I found that there are two config files in my zabbix server, so i decide to do a fresh installation. Now i am able to see the Heap Space Usage. But i am not able to retrieve the some of the other data like Learn Stat,Cache and tomcat.

The error says,
13764:20140613:004440.493 item [192.168.80.188:jmx["Catalina:type=ThreadPool,name=ajp-bio-8007","currentThreadCount"]] became not supported: Catalina:type=ThreadPool,name=ajp-bio-8007
 13764:20140613:004440.494 item [192.168.80.188:jmx["Catalina:type=ThreadPool,name=ajp-bio-8007","currentThreadsBusy"]] became not supported: Catalina:type=ThreadPool,name=ajp-bio-8007
 13764:20140613:004440.494 item [192.168.80.188:jmx["Catalina:type=ThreadPool,name=ajp-bio-8007","maxThreads"]] became not supported: Catalina:type=ThreadPool,name=ajp-bio-8007
 13766:20140613:004510.516 item [192.168.80.188:jmx["Catalina:type=GlobalRequestProcessor,name=ajp-bio-8007","errorCount"]] became not supported: Catalina:type=GlobalRequestProcessor,name=ajp-bio-8007
 13766:20140613:004510.516 item [192.168.80.188:jmx["Catalina:type=GlobalRequestProcessor,name=ajp-bio-8007","processingTime"]] became not supported: Catalina:type=GlobalRequestProcessor,name=ajp-bio-8007
 13766:20140613:004510.517 item [192.168.80.188:jmx["Catalina:type=GlobalRequestProcessor,name=ajp-bio-8007","requestCount"]] became not supported: Catalina:type=GlobalRequestProcessor,name=ajp-bio-8007
 13766:20140613:004510.517 item [192.168.80.188:jmx["blackboard.learn:name=stats","ActiveAuthenticatedSessions"]] became not supported: blackboard.learn:name=stats
 13766:20140613:004510.518 item [192.168.80.188:jmx["blackboard.learn:name=stats","ActiveSessions"]] became not supported: blackboard.learn:name=stats
 13766:20140613:004510.518 item [192.168.80.188:jmx["blackboard.learn:name=stats","InactiveAuthenticatedSessions"]] became not supported: blackboard.learn:name=stats
 13766:20140613:004510.519 item [192.168.80.188:jmx["blackboard.learn:name=stats","InactiveSessions"]] became not supported: blackboard.learn:name=stats
 13766:20140613:004510.519 item [192.168.80.188:jmx["blackboard.learn:name=stats","UserActivitiesPerHour"]] became not supported: blackboard.learn:name=stats
 13764:20140613:010010.970 item [192.168.80.188:jmx["blackboard.learn:name=stats","AssessmentAttemptsInPastHour"]] became not supported: blackboard.learn:name=stats
 13764:20140613:010010.970 item [192.168.80.188:jmx["blackboard.learn:name=stats","AvailableCourses"]] became not supported: blackboard.learn:name=stats
 13764:20140613:010010.970 item [192.168.80.188:jmx["blackboard.learn:name=stats","AvailableUsers"]] became not supported: blackboard.learn:name=stats
 13764:20140613:010010.970 item [192.168.80.188:jmx["blackboard.learn:name=stats","UnavailableCourses"]] became not supported: blackboard.learn:name=stats
 13764:20140613:010010.970 item [192.168.80.188:jmx["blackboard.learn:name=stats","UnavailableUsers"]] became not supported: blackboard.learn:name=stats
 13766:20140613:011801.567 item [192.168.80.188:assessment_cache_hit_ratio] became not supported: Cannot evaluate function [last()]
 13766:20140613:011801.568 item [192.168.80.188:attribute_cache_hit_ratio] became not supported: Cannot evaluate function [last()]
 13765:20140613:011806.568 item [192.168.80.188:authenticationProvider_cache_hit_ratio] became not supported: Cannot evaluate function [last()]
 13765:20140613:011806.569 item [192.168.80.188:bbSessionImpl_cache_hit_ratio] became not supported: Cannot evaluate function [last()]
 13764:20140613:011811.571 item [192.168.80.188:jmx["net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=AssessmentCache","CacheHits"]] became not supported: net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=AssessmentCache
 13764:20140613:011811.571 item [192.168.80.188:jmx["net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=AssessmentCache","CacheMisses"]] became not supported: net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=AssessmentCache
 13764:20140613:011811.572 item [192.168.80.188:jmx["net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=AssessmentCache","InMemoryHits"]] became not supported: net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=AssessmentCache
 13764:20140613:011811.573 item [192.168.80.188:jmx["net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=AssessmentCache","OnDiskHits"]] became not supported: net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=AssessmentCache
 13764:20140613:011811.573 item [192.168.80.188:jmx["net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=blackboard.platform.session.impl.BbSessionImpl","CacheHits"]] became not supported: net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=blackboard.platform.session.impl.BbSessionImpl
 13764:20140613:011811.573 item [192.168.80.188:jmx["net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=blackboard.platform.session.impl.BbSessionImpl","CacheMisses"]] became not supported: net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=blackboard.platform.session.impl.BbSessionImpl
 13764:20140613:011811.574 item [192.168.80.188:jmx["net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=blackboard.platform.session.impl.BbSessionImpl","InMemoryHits"]] became not supported: net.sf.ehcache:type=CacheStatistics,CacheManager=CacheEhImpl,name=blackboard.platform.session.impl.BbSessionImpl

Do you have any idea about this error?  It looks like those items are no longer available.

And i would like to check with you if there is any official installation guide for zabbix server and zabbix agent.  I accidentally created two config files under /etc/zabbix and /usr/local/zabbix . 

Again, thank you very much for kind assistance.

**Comment by threesir** [comment]
Any idea why like this?  It says item not support, what should i do to change the item key value?

![item not supported](https://cloud.githubusercontent.com/assets/7834207/3282672/ee967f04-f4f9-11e3-80ce-4811d821007b.PNG)

**Comment by lguoyu** [comment]
What's the version of your Learn?
You need to install https://github.com/blackboard/zabbix-ext/tree/develop/templates/blackboard_learn/b2 depending on your Learn version to instrument the statistics in your last comment. Use the one in sp10 if your Learn is SP10 - SP14, use 201404 for April release.

In terms of the statistics of caches, it's fine that some of the items do not work since caches are not created until the first operation is performed.

For the statistics of tomcat, it depends on your ajp port of you tomcat(before SP14), use the proper template according to your Learn version and ajp port.

**Comment by threesir** [comment]
Hi Guo  Yu,

Still did not catch up the data.  Is there any official document you can share with me? or is there any website or installation guide from other people?

Thank You!
BL

**Comment by lguoyu** [comment]
You can find out official documents on www.zabbix.com.

Checkout the mbeans exposed by your Learn with JConsole too, you should be able to see the mbeans in JConsole if your Learn is configured properly.
