### ISSUE TITLE
Escaping quotes in keys

### ISSUE THREAD

**Issue by eguilder** [blackboard/zabbix-ext#4]
In version Apr-2014 with Tomcat 7 the beans must have the name in quotes when the name contains any non-alphanumeric characters and they need to have the quotes escaped with a backslash, otherwise JMX will return an exception. As supplied the Tomcat Apr-2014 template items won't work by default.

This key doesn't work:
jmx["Catalina:type=ThreadPool,name=http-nio-8443","maxThreads"]
This key works:
jmx["Catalina:type=ThreadPool,name=\"http-nio-8443\"","maxThreads"]

This can be seen in a raw JMX exchange:

[root@zabbix_server ~]# java -jar jmxterm-1.0-alpha-4-uber.jar
Welcome to JMX terminal. Type "help" for available commands.
$>open Apr2014Dev:10052
# Connection to Apr2014Dev:10052 is opened

$>domain Catalina
# domain is set to Catalina

$>bean Catalina:type=GlobalRequestProcessor,name=http-nio-8443
# InstanceNotFoundException: Catalina:type=GlobalRequestProcessor,name=http-nio-8443

$>bean Catalina:type=GlobalRequestProcessor,name="http-nio-8443"
# bean is set to Catalina:type=GlobalRequestProcessor,name="http-nio-8443"

**Comment by ntatsumi** [comment]
Fixed: https://github.com/blackboard/zabbix-ext/commit/0237e429bf9bf873ef46d99f037af643ef75ee77
